# =========
# REDIRECTS
# =========

[[redirects]]
from = "/qr/1"
to = "/"
status = 301

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

# -------------------
# PLUGIN - LIGHTHOUSE
# -------------------

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
